Repository DFE-Digital/curriculum-materials, pull requests merged in 2020-03, with the labels that each got.

#103 Fix ordering and use a counter to mark lesson parts
  app/controllers/teachers/lessons_controller.rb
  app/controllers/teachers/units_controller.rb
  app/models/lesson.rb
  app/models/lesson_part.rb
  app/presenters/teachers/lesson_contents_presenter.rb
  app/views/teachers/lessons/_lesson_contents.slim
  spec/models/lesson_part_spec.rb
  spec/models/unit_spec.rb
  spec/presenters/teachers/lesson_contents_presenter_spec.rb
  spec/views/teachers/lessons/_lesson_contents.slim_spec.rb
Labels: tech debt

#104 Fix various minor display issues
  app/helpers/teachers/lessons_helper.rb
  app/views/teachers/lessons/_lesson_contents.slim
  app/webpacker/styles/_activity-choices.scss
  app/webpacker/styles/application.scss
Labels: bug

#116 Fix for IE11, hide icons and fall back to default
  app/webpacker/styles/_lessons.scss
Labels: bug

#121 Add rubyzip gem to fix staging
  Gemfile
  Gemfile.lock
Labels: bug

#118 Add subject key stage and year attributes
  app/controllers/api/v1/complete_curriculum_programmes_controller.rb
  app/controllers/api/v1/subjects_controller.rb
  app/controllers/api/v1/units_controller.rb
  app/models/complete_curriculum_programme.rb
  app/models/school_year.rb
  app/models/subject.rb
  app/models/unit.rb
  app/serializers/complete_curriculum_programme_serializer.rb
  app/serializers/subject_serializer.rb
  app/serializers/unit_serializer.rb
  config/routes.rb
  db/migrate/20200123094856_create_subjects.rb
  db/migrate/20200123094857_create_complete_curriculum_programmes.rb
  db/migrate/20200306141111_add_key_stage_and_year_attributes.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/data/history/the-norman-invasion.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings.yml
  db/seeds/seeder.rb
  db/seeds/seeders/ccp_seeder.rb
  db/seeds/seeders/unit_seeder.rb
  db/seeds/subjects.rb
  docs/swagger/v1/swagger.json
  spec/factories/complete_curriculum_programme.rb
  spec/factories/subjects.rb
  spec/factories/unit.rb
  spec/integration/api/v1/complete_curriculum_programmes_spec.rb
  spec/integration/api/v1/subjects_spec.rb
  spec/models/complete_curriculum_programme_spec.rb
  spec/models/school_year_spec.rb
  spec/models/subject_spec.rb
  spec/models/unit_spec.rb
  spec/support/api_examples.rb
  spec/swagger_helper.rb
Labels: enhancement

#131 Add position to the lesson seed attributes
  db/seeds/seeders/lesson_seeder.rb
Labels: bug

#128 Split the supplied presentation into activities
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/1/how-the-anglo-saxons-came-to-england/slides.odp
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/1/keyword-quiz/slides.odp
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/1/understand-the-bayeux-tapestry/slides.odp
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/2/understand-the-context-of-the-succession-crisis-of-1066/slides.odp
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/3/qualities-of-a-medieval-king/slides.odp
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/4/evaluate-the-candidates/slides.odp
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/5/strongest-and-weakest-contenders/slides.odp
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/5/understand-propaganda/slides.odp
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/5/write-about-a-king/slides.odp
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/6/who-should-be-the-next-king/slides.odp
Labels: content

#150 Require basic auth only in teacher/pages controllers
  app/controllers/application_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/teachers/base_controller.rb
Labels: bug

#148 Add a first draft of the README
  .github/CONTRIBUTING.md
  LICENCE
  README.md
  docs/schema.png
Labels: documentation

#155 🐛 Download failing due to wrong enumerator
  app/utilities/resource_packager.rb
Labels: bug

#162 Add handover documents
  README.md
  docs/Heroku.md
  docs/Seeds.md
Labels: documentation

#167 More responsiveness tweaks to lesson contents
  app/views/teachers/lessons/_lesson_contents.slim
  app/webpacker/styles/_lesson-parts.scss
  app/webpacker/styles/_lessons.scss
  app/webpacker/styles/application.scss
  spec/views/teachers/lessons/_lesson_contents.slim_spec.rb
Labels: tech debt

#169 Adds spinner to download screens
  app/views/teachers/downloads/failed.slim
  app/views/teachers/downloads/pending.slim
  app/webpacker/images/loading-spinner.gif
  app/webpacker/styles/_downloads.scss
  app/webpacker/styles/application.scss
Labels: enhancement

#171 Bugfix slide deck no file
  app/utilities/resource_packager.rb
  spec/utilities/resource_packager_spec.rb
Labels: bug

#173 🐛 e2e est unit contains lessons
  cypress/integration/Unit.spec.js
  cypress/support/commands.js
Labels: bug
