Repository DFE-Digital/curriculum-materials, pull requests merged in 2020-02, with the labels that each got.

#39 Add create and update API actions
  app/controllers/api/base_controller.rb
  app/controllers/api/v1/complete_curriculum_programmes_controller.rb
  app/controllers/api/v1/lessons_controller.rb
  app/controllers/api/v1/units_controller.rb
  config/routes.rb
  docs/swagger/v1/swagger.json
  spec/integration/api/v1/complete_curriculum_programmes_spec.rb
  spec/integration/api/v1/lessons_spec.rb
  spec/integration/api/v1/units_spec.rb
  spec/support/api_examples.rb
Labels: enhancement

#44 Remove duplication from API docs by using schemas
  app/controllers/api/v1/lessons_controller.rb
  app/controllers/api/v1/units_controller.rb
  docs/swagger/v1/swagger.json
  spec/integration/api/v1/complete_curriculum_programmes_spec.rb
  spec/integration/api/v1/lessons_spec.rb
  spec/integration/api/v1/units_spec.rb
  spec/swagger_helper.rb
Labels: documentation

#61 ✨ Support print of lesson plan page
  app/controllers/teachers/lessons_controller.rb
  app/views/layouts/print.slim
  app/views/teachers/lessons/_core_knowledge.slim
  app/views/teachers/lessons/_downloads.slim
  app/views/teachers/lessons/_lesson_contents.slim
  app/views/teachers/lessons/print.slim
  app/views/teachers/lessons/show.slim
  app/webpacker/packs/print.js
  app/webpacker/styles/_print.scss
  app/webpacker/styles/application.scss
  config/locales/en.yml
  config/routes.rb
  spec/controllers/teachers/lessons_controller_spec.rb
  spec/features/lessons/print_spec.rb
  spec/routing/teachers_lessons_routing_spec.rb
  spec/views/teachers/lessons/_lesson_contents.html.erb_spec.rb
  spec/views/teachers/lessons/print.html.erb_spec.rb
Labels: enhancement

#99 Add actual lesson to seeds
  app/helpers/teachers/lessons_helper.rb
  app/presenters/teachers/lesson_contents_presenter.rb
  app/webpacker/images/activity-icons/card-sort.png
  app/webpacker/images/activity-icons/construction.png
  app/webpacker/images/activity-icons/do-it-now.png
  app/webpacker/images/activity-icons/drawing.png
  app/webpacker/images/activity-icons/feedback.png
  app/webpacker/images/activity-icons/formative.png
  app/webpacker/images/activity-icons/group.png
  app/webpacker/images/activity-icons/guided-reading.png
  app/webpacker/images/activity-icons/individual.png
  app/webpacker/images/activity-icons/mind-map.png
  app/webpacker/images/activity-icons/pair.png
  app/webpacker/images/activity-icons/plenary.png
  app/webpacker/images/activity-icons/poster.png
  app/webpacker/images/activity-icons/practical.png
  app/webpacker/images/activity-icons/reading.png
  app/webpacker/images/activity-icons/teacher-instruction.png
  app/webpacker/images/activity-icons/teacher.png
  app/webpacker/images/activity-icons/verbal-recap.png
  app/webpacker/images/activity-icons/whole.png
  app/webpacker/images/activity-icons/worksheet.png
  app/webpacker/images/activity-icons/writing.png
  app/webpacker/images/placeholder-icons/thumb-doc.png
  app/webpacker/images/placeholder-icons/thumb-group-reading.png
  app/webpacker/images/placeholder-icons/thumb-mp3.png
  app/webpacker/images/placeholder-icons/thumb-mp4.png
  app/webpacker/images/placeholder-icons/thumb-pair-reading.png
  app/webpacker/images/placeholder-icons/thumb-ppt.png
  app/webpacker/images/placeholder-icons/thumb-practical.png
  app/webpacker/images/placeholder-icons/thumb-whole-class.png
  app/webpacker/images/placeholder-icons/thumb-worksheet.png
  config/locales/en.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/1/how-the-anglo-saxons-came-to-england.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/1/keyword-quiz.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/1/understand-the-bayeux-tapestry.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/2/understand-the-context-of-the-succession-crisis-of-1066.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/3/qualities-of-a-medieval-king.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/4/evaluate-the-candidates.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/5/strongest-and-weakest-contenders.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/5/understand-propaganda.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/5/write-about-a-king.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/contenders-to-the-throne/6/who-should-be-the-next-king.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/harolds-march-south.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/norman-preparations-and-forces.yml
  db/seeds/data/history/the-norman-invasion/the-battle-of-hastings/prelude-to-the-battle.yml
  db/seeds/seeders/activity_seeder.rb
  db/seeds/teaching_methods.rb
  spec/features/lessons/knowledge_overview_tab_spec.rb
  spec/presenters/teachers/lesson_contents_presenter_spec.rb
Labels: content
